Add `BitNumericTextField` component (#1846)
bitfoundation/bitplatform pull request #2093
Opened 2022-05-28 19:52 UTC by Cyrus-Sushiant

This closes #1846

2022-05-29 07:44 UTC, maryamhdr requested changes

2022-05-29 07:44 UTC, maryamhdr commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/NumericTextField/BitNumericTextField.Fluent.scss
> +}
plz reduce the specificity level using specific class names

2022-05-29 10:03 UTC, msynk submitted a review, later dismissed

2022-05-30 10:22 UTC, maryamhdr approved these changes

2022-05-30 12:32 UTC, merged