remove culture dependent samples #2090
bitfoundation/bitplatform pull request #2127
Opened 2022-05-30 14:44 UTC by Md23Mh

This closes #2090.

2022-05-30 17:57 UTC, ysmoradi submitted a review, later dismissed

2022-05-31 09:30 UTC, maryamhdr submitted a review, later dismissed

2022-05-31 10:29 UTC, msynk requested changes

2022-05-31 10:29 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/DatePicker/BitDatePickerDemo.razor
> +            <div class="example-desc">Please note that in order to use this sample we needed to set InvariantGlobalization to false in project setting, which in turn caused extra weight on the websit
please use these sentences instead:

`Please note to reduce the download size of this page, the sample is not implemented here. In order to use this example, it's required to set InvariantGlobalization to false in the project setting, which causes an extra download size for the website.`

2022-05-31 18:05 UTC, ysmoradi approved these changes

2022-06-01 10:16 UTC, merged