Resolve issue sign up without accepting the privacy policy #2158
bitfoundation/bitplatform pull request #2170
Opened 2022-06-08 20:44 UTC by Cyrus-Sushiant

This closes #2158

2022-06-08 20:49 UTC, maryamhdr submitted a review, later dismissed

2022-06-09 06:40 UTC, msynk requested changes

2022-06-09 06:40 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
> +        if (IsLoading || SignUpModel.IsAcceptPrivacy is false)
this is like a workaround. I don't like it.
shouldn't we try to validate the form instead?

2022-06-09 06:59 UTC, msynk approved these changes

2022-06-09 07:00 UTC, merged