Create ``BitPlatformWebsite`` project
bitfoundation/bitplatform pull request #2175
Opened 2022-06-10 08:23 UTC by msangtarash

this closes #1890

2022-06-10 08:34 UTC, ysmoradi requested changes

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Api/appsettings.json
> +    "UploadPath": "./BitFileUploaderFiles/"
Please remove this `UploadPath`

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Footer.razor.min.css
> +﻿@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2/AxiformaExtraBoldItalic.woff2") format("woff2");font-weight:800;}@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2
Don't push this file. Check git ignore settings

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Footer.razor.css
> +﻿@font-face {
Don't push this file. Check git ignore settings

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Footer.razor.cs
> +        protected override void OnInitialized()
Remove extra override

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Header.razor.cs
> +        {
Remove extra override

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Header.razor.css
> +﻿@font-face {
Don't push this. Check git ignore settings

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/Header.razor.min.css
> +﻿@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2/AxiformaExtraBoldItalic.woff2") format("woff2");font-weight:800;}@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2
Don't push this. Check git ignore settings

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/NotFoundComponent.razor.css
> +﻿@font-face {
Don't push this. Check git ignore settings

2022-06-10 08:34 UTC, ysmoradi commented on src/WebSite/Bit.Platform.WebSite/Web/Components/NotFoundComponent.razor.min.css
> +﻿@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2/AxiformaExtraBoldItalic.woff2") format("woff2");font-weight:800;}@font-face{font-family:"Axiforma";src:url("../fonts/Axiforma/woff2
Don't push this. Check git ignore settings

2022-06-13 07:25 UTC, msynk commented
@ysmoradi 
plz re-review this PR after new changes

2022-06-13 07:38 UTC, msynk requested changes

2022-06-13 07:38 UTC, msynk commented on src/WebSite/Bit.Platform.WebSite/Web/wwwroot/scripts/app.js
> +"use strict";
this file shouldn't be in the repo.

2022-06-13 07:41 UTC, ysmoradi requested changes
Bit.Platform.WebSite.Web.sln's location is wrong

2022-06-13 20:14 UTC, msynk approved these changes

2022-06-13 22:07 UTC, ysmoradi approved these changes

2022-06-14 08:13 UTC, msangtarash commented
PING !

2022-06-14 16:22 UTC, merged