Implement the project template of the todo template (#1793 )
bitfoundation/bitplatform pull request #2211
Opened 2022-06-16 09:05 UTC by MeysamBahadori

this closes [#](https://github.com/bitfoundation/bitplatform/issues/2179)1793

2022-06-16 10:23 UTC, msynk reviewed
@MeysamBahadori 
please update this PR based on our conversation :)

2022-06-16 11:57 UTC, MeysamBahadori commented
> @MeysamBahadori please update this PR based on our conversation :)

Ok

2022-06-19 12:29 UTC, MeysamBahadori commented
Ready for review...

2022-06-20 06:09 UTC, MeysamBahadori commented
BlazorMode and WebAppDeploymentType symbols removed.

2022-06-20 13:02 UTC, msynk commented
@MeysamBahadori 
plz resolve the conflicts

2022-06-20 13:26 UTC, MeysamBahadori commented
Plz review again...

2022-06-22 16:50 UTC, msynk requested changes

2022-06-22 16:50 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Api/Startup/Middlewares.cs
> +
plz remove this change

2022-06-22 16:50 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Shared/Infra/BuildConfigurationModeDetector.cs
> +                #else
plz correct the code formatting in this line

2022-06-22 16:50 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Extensions/IServiceCollectionExtensions.cs
> -
plz remove this change

2022-06-22 16:50 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Program.cs
> +
plz remove this change

2022-06-22 16:50 UTC, msynk commented on src/Bit.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TodoTemplate.nuget", "Tooling\Bit.Tooling.Templates\TodoTemplate\TodoTemplate.nuget.csproj", "{95571715-5D44-478C-9681-A35543A2A5F5}"
isn't this project renamed to `TodoTemplate.ProjectTemplate.csproj`?

2022-06-23 06:08 UTC, msynk approved these changes

2022-06-23 06:09 UTC, merged