Fix month names issue for the custom CultureInfo in the `BitDatePicker` demo page (#2073)
bitfoundation/bitplatform pull request #2237
Opened 2022-06-22 07:55 UTC by sajadkardel

this closes #2073

2022-06-22 08:20 UTC, sajadkardel commented
To review the result of these changes, you need to change parts of the project settings. The image below may help you to review the changes -_-

<img width="315" alt="Untitled" src="https://user-images.githubusercontent.com/62190682/174979487-4055914d-bce1-43dd-b410-c27f0c61e36e.png">

(the colorful border is flex box)

2022-06-22 11:28 UTC, msynk approved these changes

2022-06-22 11:29 UTC, msynk commented
@sajadkardel 
could you plz add the full month name as a title (tooltip), since in your solution you used the ellipsis cut-off

2022-06-23 09:36 UTC, msynk requested changes

2022-06-23 09:43 UTC, sajadkardel commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/DatePicker/BitDatePicker.razor
> +                                                    title="@Culture?.DateTimeFormat.GetMonthName(monthIndex)"
also `CheckMonthForMaxAndMinDate` is called 2 time in this section.
change this too or not?
@msynk

2022-06-23 09:44 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/DatePicker/BitDatePicker.razor
> +                                                    title="@Culture?.DateTimeFormat.GetMonthName(monthIndex)"
not related to this issue

2022-06-24 05:58 UTC, merged