Extend the demo page for the BitDataGrid component (#2357)
bitfoundation/bitplatform pull request #2365
Opened 2022-07-03 09:09 UTC by MeysamBahadori

This closes #2357

2022-07-03 10:23 UTC, msynk requested changes

2022-07-03 10:23 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +  background-image: url('data:image/svg+xml;utf8,<svg xmlns=""http://www.w3.org/2000/svg"" class=""h-6 w-6"" fill=""none"" viewBox=""0 0 24 24"" stroke=""currentColor"" stroke-width=""2""> <path stro
please update this part based on the updated content of the actual .scss file

2022-07-03 10:23 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +                <input type = ""search"" autofocus @bind = ""nameFilter"" @bind:event=""oninput"" />
please update this part based on the updated content of the actual .razor file

2022-07-03 10:23 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +    IQueryable<Country> data;
please use a proper name for this variable

2022-07-03 10:37 UTC, ysmoradi commented
The virtualization sample needs to retrieve data from the remote data source

2022-07-03 16:18 UTC, ysmoradi requested changes

2022-07-03 16:18 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +        var url = NavManager.GetUriWithQueryParameters("http://api.fda.gov/food/enforcement.json", new Dictionary<string, object?>
Use https://

2022-07-03 16:18 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +        ServicePointManager.ServerCertificateValidationCallback = delegate (object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
?

2022-07-03 16:18 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +            return new BitDataGridItemsProviderResult<FoodRecall>() { Items=new List<FoodRecall>() { } , TotalItemCount=0 };
Format the code please

2022-07-03 16:18 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +            return new BitDataGridItemsProviderResult<FoodRecall>() { Items=new List<FoodRecall>() { } , TotalItemCount=0 };
Use System.Text.Json Source Generator to improve the performance of this (and the rest of http calls if any)

2022-07-04 06:26 UTC, MeysamBahadori reviewed
Ready for review

2022-07-04 11:40 UTC, MeysamBahadori commented
Ready for review

2022-07-04 13:25 UTC, MeysamBahadori commented
plz review again @ysmoradi

2022-07-04 13:47 UTC, msynk approved these changes

2022-07-04 13:47 UTC, merged