Add Generic Class Support in AutoInject (#2300)
bitfoundation/bitplatform pull request #2371
Opened 2022-07-03 13:06 UTC by milad-karimifard

this closes #2300

2022-07-03 16:16 UTC, ysmoradi submitted a review, later dismissed

2022-07-03 17:59 UTC, msynk requested changes

2022-07-03 17:59 UTC, msynk commented on src/SourceGenerators/Bit.SourceGenerators/AutoInject/AutoInjectNormalClassHandler.cs
> +        return $"{classSymbol.Name}{genericTypesName}";
please change this method's implementation based on a similar method in the `ComponentDetailsController` of the Bit.BlazorUI Playground (the GetTypeName method in the controller).

2022-07-03 18:22 UTC, ysmoradi approved these changes

2022-07-04 03:23 UTC, msynk approved these changes

2022-07-04 03:24 UTC, merged