add placeholder numerictextfiled demo #2245
bitfoundation/bitplatform pull request #2432
Opened 2022-07-08 21:49 UTC by Md23Mh

This closes #2245

2022-07-09 19:35 UTC, msynk commented
this PR is a duplicate of #2431, so I've closed it.

2022-07-09 19:40 UTC, msynk approved these changes

2022-07-09 19:40 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/NumericTextField/BitNumericTextFieldDemo.razor
> +                <BitTextField Label="With Placeholder" Placeholder="0"></BitTextField>
please use a better Placeholder. something like `please enter a number`

2022-07-09 20:32 UTC, msynk requested changes

2022-07-09 20:32 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/NumericTextField/BitNumericTextFieldDemo.razor.cs
> +<BitTextField Label=""With Placeholder"" Placeholder=""0""></BitTextField>";
plz update the example code too

2022-07-11 06:17 UTC, ysmoradi approved these changes

2022-07-11 12:38 UTC, merged