Enhance the `Jalali BitDatePicker` in `Playground` project
bitfoundation/bitplatform pull request #2451
Opened 2022-07-10 16:00 UTC by msangtarash

this closes #2420

2022-07-10 16:54 UTC, ysmoradi approved these changes

2022-07-10 16:54 UTC, ysmoradi commented on src/BlazorUI/Bit.BlazorUI.Tests/Pickers/BitDatePickerTests.cs
> +           (Action<ComponentParameterCollectionBuilder<BitDatePickerTest>>)(           parameters =>
Revet this

2022-07-11 13:31 UTC, msynk requested changes

2022-07-11 16:58 UTC, msangtarash commented on src/BlazorUI/Bit.BlazorUI/Utils/CultureInfoHelper.cs
> +            "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند", ""
I have no idea.
The only value I can offer is using numbers
1 2 3 ...12 :)

2022-07-11 17:17 UTC, msynk commented on src/BlazorUI/Bit.BlazorUI/Utils/CultureInfoHelper.cs
> +            "فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن", "اسفند", ""
hmm, what about something like these:
"فرور", "ارد", "خرد", "تیر", "مرد", "شهر", "مهر", "آبا", "آذر", "دی", "بهم", "اسف"

2022-07-11 18:00 UTC, ysmoradi commented on src/BlazorUI/Bit.BlazorUI/Utils/CultureInfoHelper.cs
> -        cultureInfo.DateTimeFormat.AbbreviatedDayNames = new[]
?

2022-07-11 18:01 UTC, ysmoradi commented on src/BlazorUI/Bit.BlazorUI/Utils/CultureInfoHelper.cs
> +        cultureInfo.DateTimeFormat.PMDesignator = "ب.ظ";
Do you mean GH.Z & B.Z?

2022-07-11 18:01 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DatePicker/BitDatePickerDemo.razor
> +    <ComponentExampleBox Title="Jalali BitDatePicker with Finglish names" HTMLSourceCode="@example4HTMLCode" ExampleId="example4">
There's no need to CultureInfoHelper code anymore

2022-07-12 08:18 UTC, msynk approved these changes

2022-07-12 08:20 UTC, merged