Lighthouse optimization on the `TodoTemplate` project (#2436)
bitfoundation/bitplatform pull request #2455
Opened 2022-07-10 19:44 UTC by maryamhdr

this closes #2436

2022-07-10 19:45 UTC, ysmoradi submitted a review, later dismissed

2022-07-11 12:32 UTC, msynk requested changes

2022-07-11 12:32 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/Web/Pages/EditProfile.razor
> +                        <img src="@ProfileImageUrl" class="profile-img" alt="user profile image"/>
again:
user  ==>>  User

(capital U)

2022-07-11 17:12 UTC, msynk approved these changes

2022-07-11 17:12 UTC, merged