Set application mode based on UserAgent in AdminPanel (#2474)
bitfoundation/bitplatform pull request #2568
Opened 2022-07-16 18:52 UTC by milad-karimifard

this closes #2474

2022-07-16 19:40 UTC, msynk requested changes

2022-07-16 19:40 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/Web/Extensions/HttpRequestExtensions.cs
> +        var isGoogleBot = IsGoogleBot(agent);
there is no need to define these simple methods and complicate code like this.
plz remove these methods and directly check the user-agent here.

2022-07-16 19:40 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/Web/Extensions/HttpRequestExtensions.cs
> +    public static bool IsSearchEngineBot(this HttpRequest request)
please rename this method to `ShouldRenderStaticMode`

2022-07-16 19:40 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/Web/Extensions/HttpRequestExtensions.cs
> +        var formattedUserAgent = userAgent.ToLower();
either remove this magic line from this method or rename the method to reflect this behavior (like `GetLoweredUserAgent`)

2022-07-17 04:31 UTC, ysmoradi approved these changes

2022-07-17 05:25 UTC, msynk approved these changes

2022-07-17 05:26 UTC, merged