Changed the public access modifier to internal in all extension classes (#2086)
bitfoundation/bitplatform pull request #2572
Opened 2022-07-16 19:47 UTC by mohabbati

This closes #2086

2022-07-16 20:10 UTC, msynk requested changes

2022-07-16 20:10 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Extensions/EnumExtensions.cs
> +}
instead of redefining this class use `[assembly: InternalsVisibleTo("Bit.BlazorUI.Tests")]`

2022-07-16 20:10 UTC, msynk commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Extensions/StringExtensions.cs
> +}
again, instead of redefining this class use `[assembly: InternalsVisibleTo("Bit.BlazorUI.Tests")]`

2022-07-17 09:50 UTC, msynk commented
@mohabbati 
did you try to build the project and run the tests?
I'm pretty sure that some of these extension methods are also used in the Tests project.

2022-07-17 10:02 UTC, mohabbati commented
> Tests project.

All projects in the `Bit.BlazorUI` solution were built successfully. And 2384 tests passed after running tests.

2022-07-17 10:59 UTC, msynk commented
you are right, there is already an `InternalsVisibleTo("Bit.BlazorUI.Tests")` set in the BitColor.cs file.

2022-07-17 11:00 UTC, msynk requested changes

2022-07-17 11:00 UTC, msynk commented on src/BlazorUI/Bit.BlazorUI/Extensions/StringExtensions.cs
> +[assembly: InternalsVisibleTo("Bit.BlazorUI.Playground.Web")]
since this is an assembly level attribute, you need to apply it once.
please remove this duplicate line.

2022-07-17 15:16 UTC, msynk approved these changes

2022-07-17 15:17 UTC, merged