Update route approach (#2546)
bitfoundation/bitplatform pull request #2672
Opened 2022-07-22 18:40 UTC by saleh-ghezelbash

This closes #2546

2022-07-22 19:13 UTC, msynk approved these changes

2022-07-23 09:00 UTC, msynk requested changes
it seems there are still other controllers that require these improvements

2022-07-23 15:01 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +            var url = NavManager.GetUriWithQueryParameters(""/api/Products/GetProducts"", query);
It was working without starting / before
Do we need this now?

2022-07-23 15:20 UTC, ysmoradi approved these changes

2022-07-23 17:04 UTC, msynk requested changes

2022-07-23 17:04 UTC, msynk commented on src/Sales/Bit.Sales.WebSite/Api/Controllers/ContactUsController.cs
> +[Route("api/[controller]/[action]")]
are we sure about this change?
@ysmoradi

2022-07-23 17:04 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/Api/Controllers/TodoItemController.cs
> +[Route("api/[controller]/[action]")]
again, are we sure about this one too?
@ysmoradi

2022-07-24 11:04 UTC, ysmoradi approved these changes

2022-07-24 11:20 UTC, msynk approved these changes

2022-07-24 11:20 UTC, merged