Fix the incorrect `async void` usage in the Bit Platform projects (#2765)
bitfoundation/bitplatform pull request #2772
Opened 2022-07-27 08:23 UTC by sajadkardel

this closes #2765

2022-07-27 09:06 UTC, msynk requested changes

2022-07-27 09:08 UTC, msynk commented
@sajadkardel 
please use the appropriate `WrapHandled` method for calling these methods in the razor files in the template projects.

2022-07-27 09:31 UTC, sajadkardel commented
> @sajadkardel please also use the appropriate `WrapHandled` methods for calling the methods (that you've changed) in the razor files of the bit platform projects if not used.

It was one. in the `ProductsPage.razor` file and I fixed it. @msynk

2022-07-27 10:19 UTC, msynk approved these changes

2022-07-28 06:00 UTC, ysmoradi approved these changes

2022-07-28 07:39 UTC, merged