Add cascading sample to the BitDropDown demo page #2716
bitfoundation/bitplatform pull request #2795
Opened 2022-07-27 19:08 UTC by Cyrus-Sushiant

This closes #2716

2022-07-28 05:37 UTC, ysmoradi requested changes

2022-07-28 05:37 UTC, ysmoradi commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DropDown/BitDropDownDemo.razor.cs
> +        if (string.IsNullOrEmpty(productId))
```cs
if(int.TryParse(productId, CurrentOrder.ProductId) is false)
{
	CurrentOrder.ProductId = 0;
}

CurrentOrder.ProductName = Products.FirstOrDefault(c => c.Id == CurrentOrder.ProductId)?.Name;
```

2022-07-29 14:44 UTC, ysmoradi approved these changes

2022-07-29 16:40 UTC, msynk approved these changes

2022-07-29 16:41 UTC, merged