improving the appearance of the BitDataGrid component example in the blazou UI demo project (#2718)
bitfoundation/bitplatform pull request #2796
Opened 2022-07-28 08:51 UTC by MeysamBahadori

This closes #2718

2022-07-28 11:17 UTC, ysmoradi requested changes

2022-07-28 12:20 UTC, MeysamBahadori commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor
> +                    <BitDataGridTemplateColumn Title="Flag" Align="BitDataGridAlign.Center">
All these fields are sortable

2022-07-28 12:53 UTC, msynk approved these changes

2022-07-29 18:56 UTC, msynk commented
@maryamhdr 
plz review

2022-07-29 21:53 UTC, ysmoradi submitted a review, later dismissed

2022-07-31 07:02 UTC, maryamhdr requested changes

2022-07-31 07:02 UTC, maryamhdr commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +}
plz add a blank line after declaring each CSS class block.

2022-07-31 08:12 UTC, MeysamBahadori commented on src/BlazorUI/Playground/Bit.BlazorUI.Playground/Web/Pages/Components/DataGrid/BitDataGridDemo.razor.cs
> +}
ok

2022-07-31 15:12 UTC, maryamhdr approved these changes

2022-07-31 15:13 UTC, merged