Convert hero-banner.png to webp format (#2825)
bitfoundation/bitplatform pull request #2828
Opened 2022-07-30 22:19 UTC by msynk

this closes #2825

2022-07-30 23:01 UTC, ysmoradi requested changes
I've performed that with cloud convert and it's all about less than 30KB
You can check that on https://bitplatform.dev
The PR one's is about 500KB!

2022-07-31 05:10 UTC, msynk commented
yeah, you're right, it's weird 🧐🤔

2022-07-31 06:59 UTC, maryamhdr approved these changes

2022-07-31 08:35 UTC, ysmoradi approved these changes

2022-07-31 08:59 UTC, merged