Fix localization issue with pre rendering in ``AsminPanel`` project (#2963 )
bitfoundation/bitplatform pull request #3059
Opened 2022-08-20 14:50 UTC by msangtarash

This closes #2963

2022-08-20 15:08 UTC, ysmoradi requested changes

2022-08-20 15:08 UTC, ysmoradi commented on src/Templates/AdminPanel/Bit.AdminPanel/Api/Controllers/CategoryController.cs
> +using Microsoft.Extensions.Localization;
Remove this

2022-08-20 15:54 UTC, ysmoradi approved these changes

2022-08-21 09:18 UTC, msynk approved these changes

2022-08-21 09:20 UTC, merged