Fix BitPlatform typos in all files
bitfoundation/bitplatform pull request #5542
Opened 2023-10-12 19:54 UTC by taha-ghadirian

Closes #5426

2023-10-12 20:11 UTC, msynk requested changes

2023-10-12 20:11 UTC, msynk commented on src/BlazorUI/Demo/Client/Core/Pages/TermsPage.razor
> +                Bit Platform hereby grants the user a non-exclusive, non-transferable license to use the Software, solely for the purpose of evaluating and testing the features of the bit BlazorUI De
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/BlazorUI/Demo/Client/Core/Pages/TermsPage.razor
> +                Bit Platform retains all rights, title, and interest in and to the Software, including any and all intellectual property rights.
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/BlazorUI/Demo/Client/Core/Pages/TermsPage.razor
> +                Bit platform may collect user data, including name, surname, photo, date of birth, and gender. Providing this information is optional, and bit platform will only use it for the purpos
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/BlazorUI/Demo/Client/Core/Pages/TermsPage.razor
> +                    <li>Bit platform is committed to protecting the privacy of user data.</li>
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform hereby grants the user a non-exclusive, non-transferable license to use the Software, solely for the purpose of evaluating and testing the features of the AdminPanel Demo
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform retains all rights, title, and interest in and to the Software, including any and all intellectual property rights.
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform may collect user data, including name, surname, photo, date of birth, and gender. Providing this information is optional, and bit platform will only use it for the purpos
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform does not use any Analytics tools for measuring website traffic and only uses strictly necessary cookies.
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                The Software is provided "AS IS" and without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform shall not be liable for any damages whatsoever arising out of the use of or inability to use the Software, including but not limited to direct, indirect, incidental, spec
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                This EULA shall remain in effect until 2025-12-31. Bit platform reserves the right to terminate this EULA at any time without notice. Upon termination, the user shall immediately ceas
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                If you have any questions or concerns regarding this EULA or the Privacy Policy, or if you would like to contact Bit platform for any reason, please email <BitLink Href="mailto:info@b
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/AdminPanel/Bit.AdminPanel/src/Client/Core/Pages/TermsPage.razor
> +                    <li>Bit platform is committed to protecting the privacy of user data.</li>
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                This EULA and Privacy Policy are written for individuals who use the TodoTemplate Demo Version through the <BitLink Href="https://todo.bitplatform.dev" Target="_blank">todo.bitplatfor
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                This End-User License Agreement (EULA) is a legal agreement between you (the "user") and Bit platform, located at Sixmastraat 15, 8932 PA Leeuwarden, Netherlands, with phone number <B
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform hereby grants the user a non-exclusive, non-transferable license to use the Software, solely for the purpose of evaluating and testing the features of the TodoTemplate De
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform retains all rights, title, and interest in and to the Software, including any and all intellectual property rights.
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform may collect user data, including name, surname, photo, date of birth, and gender. Providing this information is optional, and Bit platform will only use it for the purpos
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform does not use any Analytics tools for measuring website traffic and only uses strictly necessary cookies.
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                The Software is provided "AS IS" and without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose
Lowercase all the way plz

2023-10-12 20:11 UTC, msynk commented on src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Pages/TermsPage.razor
> +                Bit platform shall not be liable for any damages whatsoever arising out of the use of or inability to use the Software, including but not limited to direct, indirect, incidental, spec
Lowercase all the way plz

2023-10-12 20:32 UTC, taha-ghadirian commented
Requested changes applied. 

However, As a suggestion I guess starting sentences with uppercase letters, makes the code and documents easier to read and understand.

2023-10-12 21:01 UTC, msynk commented
@taha-ghadirian Thanks.
I understand your suggestion, but in this case, since the `bit platform` is a special name, its capitalization should not be changed anywhere.

2023-10-12 21:05 UTC, msynk requested changes

2023-10-12 21:05 UTC, msynk commented on src/BlazorUI/Demo/Client/Core/Pages/TermsPage.razor
> +                bit platform may collect user data, including name, surname, photo, date of birth, and gender. Providing this information is optional, and bit platform will only use it for the purpos
you missed one here

2023-10-13 11:10 UTC, msynk approved these changes

2023-10-13 16:45 UTC, merged