Add session management to Boilerplate ()
bitfoundation/bitplatform pull request #8020
Opened 2024-07-16 16:14 UTC by ysmoradi

This closes #8019

2024-07-16 18:03 UTC, msangtarash commented on src/Templates/Boilerplate/Bit.Boilerplate/src/Client/Boilerplate.Client.Core/Components/Pages/Identity/Profile/DeleteAccountConfirmModal.razor.cs
> +        await AuthenticationManager.SignOut(CurrentCancellationToken);
No need to call UserController.SignOut inside AuthenticationManager

2024-07-16 18:04 UTC, msangtarash commented on src/Templates/Boilerplate/Bit.Boilerplate/src/Client/Boilerplate.Client.Core/Services/AuthenticationManager.cs
> +            await userController.SignOut(cancellationToken);
Call UserController.SignOut only if refresh token exists

2024-07-16 18:05 UTC, msangtarash commented on src/Templates/Boilerplate/Bit.Boilerplate/src/Server/Boilerplate.Server.Api/Controllers/Identity/UserController.cs
> +        user.Sessions = user.Sessions.Where(s => s.SessionUniqueId != Guid.Parse(User.FindFirstValue("session-id")!)).ToList();
store `Guid.Parse(User.FindFirstValue("session-id")!` in variable

2024-07-16 18:07 UTC, msangtarash commented on src/Templates/Boilerplate/Bit.Boilerplate/src/Server/Boilerplate.Server.Api/Mappers/IdentityMapper.cs
> +                            ? AppStrings.Recently
Check if static usage of AppStrings works in all scenarios

2024-07-16 18:14 UTC, msangtarash requested changes

2024-07-16 18:14 UTC, msangtarash commented on src/Templates/Boilerplate/Bit.Boilerplate/src/Server/Boilerplate.Server.Api/Controllers/Identity/IdentityController.cs
> +        if (refreshTicket?.Properties?.ExpiresUtc is not { } expiresUtc ||
if found user, but refresh token was expired, then remove session, if everything is fine, set sessions.RenewedOn, and in finally, save the user

2024-07-18 15:59 UTC, msynk approved these changes

2024-07-18 16:34 UTC, merged